# DigitalOcean App Platform Configuration for Unity Financial Network
#
# This configuration deploys the Unity Financial Network application
# directly from GitHub repository with automatic builds and deployments.
#
# Repository: https://github.com/terrizoaguimor/unity-financial-network
# Region: NYC (closest to Atlanta, as Atlanta is not available)
#
# Version: 5.0 (SEO Optimized with GitHub Integration)
# Author: Unity Financial Network Development Team

name: unity-financial-network
region: nyc  # NYC is closest to Atlanta from available regions

services:
  - name: web
    # GitHub repository configuration for automatic deployments
    github:
      repo: terrizoaguimor/unity-financial-network
      branch: master
      deploy_on_push: true  # Auto-deploy on push to master
    
    # Build configuration for Next.js application
    build_command: npm ci && npm run build
    run_command: npm start
    
    # Environment configuration
    environment_slug: node-js
    engine: nodejs
    
    # Instance sizing and scaling
    instance_size_slug: professional-xs  # Professional tier for better performance
    instance_count: 1                    # Can scale to multiple instances
    
    # HTTP configuration
    http_port: 3000
    
    # Health check configuration for monitoring
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Routing configuration
    routes:
      - path: /
        preserve_path_prefix: true
    
    # CORS configuration (optional, uncomment if needed)
    # cors:
    #   allow_origins:
    #     - prefix: https://unityfinancialnetwork.com
    #   allow_methods:
    #     - GET
    #     - POST
    #     - PUT
    #     - DELETE
    #     - OPTIONS
    #   allow_headers:
    #     - Content-Type
    #     - Authorization
    
    # Environment variables
    envs:
      # Node environment
      - key: NODE_ENV
        value: production
        
      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
        
      # Port configuration
      - key: PORT
        value: "3000"
        
      - key: HOSTNAME
        value: "0.0.0.0"
        
      # Public environment variables
      - key: NEXT_PUBLIC_TURNSTILE_SITE_KEY
        value: "0x4AAAAAABxARgHmGCOgbqUe"
        
      - key: NEXT_PUBLIC_SITE_URL
        value: "${APP_URL}"
        
      # Secret environment variables (marked as SECRET for security)
      - key: TURNSTILE_SECRET_KEY
        value: "0x4AAAAAABxARnAyKid17RihUIKY5H9qazU"
        type: SECRET
        
      - key: RESEND_API_KEY
        value: "re_GfLVHiai_An5aA8grQJmy1gHq5NVYGCtc"
        type: SECRET

# Domain configuration (add your custom domain here)
domains:
  - domain: unityfinancialnetwork.com
    type: PRIMARY
    zone: unityfinancialnetwork.com
    
# Alert configuration for monitoring
alerts:
  - rule: DEPLOYMENT_FAILED
    disabled: false
  - rule: DEPLOYMENT_LIVE
    disabled: false
  - rule: CPU_UTILIZATION
    value: 85
    window: FIVE_MINUTES
    disabled: false
  - rule: MEM_UTILIZATION
    value: 85
    window: FIVE_MINUTES
    disabled: false
  - rule: RESTART_COUNT
    value: 5
    window: FIVE_MINUTES
    disabled: false

# Future database configuration (commented for now)
# databases:
#   - name: unity-db
#     engine: PG
#     version: "15"
#     size: db-s-dev-database
#     num_nodes: 1

# Static assets configuration (if needed)
# static_sites:
#   - name: unity-assets
#     github:
#       repo: terrizoaguimor/unity-financial-network
#       branch: master
#       deploy_on_push: true
#     source_dir: public
#     output_dir: /