packages:
  - name: unity-financial-functions
    environment:
      HUBSPOT_API_KEY: ${HUBSPOT_API_KEY}
    functions:
      - name: hubspot-lead
        runtime: nodejs:18
        web: true
        webSecure: false